create sequence seq_role start 1 increment 1;
create table lembrete (id  serial not null, data_lembrete date not null, descricao varchar(255), horario_lembrete time, titulo varchar(45) not null, user_id int4, primary key (id));
create table remedio (id  serial not null, descricao varchar(255), nome varchar(255) not null, primary key (id));
create table role (id int4 not null, nome_role varchar(255), primary key (id));
create table usuario (id  serial not null, login varchar(50) not null, nome varchar(70) not null, senha varchar(70) not null, token varchar(255), primary key (id));
create table usuarios_role (usuario_id int4 not null, role_id int4 not null);
alter table usuario add constraint UK_pm3f4m4fqv89oeeeac4tbe2f4 unique (login);
alter table usuarios_role add constraint UK_krvk2qx218dxa3ogdyplk0wxw unique (role_id);
alter table usuarios_role add constraint unique_role_user unique (usuario_id, role_id);
alter table lembrete add constraint fk_user foreign key (user_id) references usuario;
alter table usuarios_role add constraint role_fk foreign key (role_id) references role;
alter table usuarios_role add constraint usuario_fk foreign key (usuario_id) references usuario;
